flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- location:
    git: https://github.com/LumiGuide/haskell-opencv.git
    commit: 9649f7cdd4b7b1f6e5ddd859d63658a33ba42b3d
- location:
    git: https://github.com/basvandijk/scientific.git
    commit: 9ef2876fe9feb5bc97b005900097462761ad12aa    
- '.'
extra-deps:
- Glob-0.7.14
- QuickCheck-2.9.2
- StateVar-1.1.0.4
- abstract-deque-0.3
- abstract-par-0.3.3
- adjunctions-4.3
- aeson-1.1.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- bindings-DSL-1.0.23
- blaze-builder-0.4.0.2
- byteable-0.1.1
- bytes-0.15.2
- cabal-doctest-1
- cassava-0.4.5.1
- cereal-0.5.4.0
- charset-0.3.7.1
- clock-0.7.2
- code-page-0.1.1
- comonad-5
- contravariant-1.4
- cpphs-1.20.2
- criterion-1.1.4.0
- cryptohash-0.11.9
- cryptonite-0.21
- distributive-0.5.2
- dlist-0.8.0.2
- erf-2.0.0.0
- exceptions-0.8.3
- fail-4.9.0.0
- free-4.12.4
- generic-deriving-1.11.1
- hashable-1.2.5.0
- haskell-src-exts-1.19.1
- hastache-0.6.1
- ieee754-0.8.0
- inline-c-0.5.6.1
- inline-c-cpp-0.1.0.0
- integer-logarithms-1.0.1
- js-flot-0.8.3
- js-jquery-3.1.1
- kan-extensions-5.0.1
- lens-4.15.1
- linear-1.20.5
- math-functions-0.2.1.0
- memory-0.14.1
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.5.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.0.0
- parallel-3.2.1.0
- parsec-3.1.11
- parsers-0.12.4
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-tdfa-1.2.2
- repa-3.4.1.2
- scientific-0.3.4.10
- semigroupoids-5.1
- semigroups-0.18.2
- statistics-0.13.3.0
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.5
- tasty-0.11.1
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-0.5.2.0
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.2
- uuid-types-1.0.3
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.4
- vector-th-unbox-0.2.1.6
- void-0.7.1
resolver: lts-7.18

